#!/usr/bin/env bash

set -a

PROJECT_HOME="${PROJECT_HOME:-/ptcolors.jl}"

if [ -f "${PROJECT_HOME}/environments/development.env" ]; then
    # shellcheck source=/dev/null
    . "${PROJECT_HOME}/environments/development.env"
fi

set +a
